### ISSUE TITLE
GEMM dimensions, TN case

### ISSUE THREAD

**Issue by newling** [baidu-research/DeepBench#13] opened 2016-11-18 05:25 UTC
There seems to be a discrepency with the dimensions printed and those passed to cublasSgemm for the TN case. I'm looking at file gemm_bench.cu. 

Effectively, at line 177 
C is  k_printed by n_printed
B is  m_printed by n_printed
A is  m_printed by k_printed

so that 
m_to_cublas, k_to_cublas = k_printed, m_printed.

This possible discrepency applies to 15 of the 78 cases.

**Comment by sharannarang** [comment] 2016-12-22 00:43
Sorry for the delayed response. You're correct that `m` and `k` aren't printed correctly for `TN` case. Thanks for pointing this out. This doesn't matter for the benchmark results since `m` & `k` are the always the same for all the GEMMs. However, I'll figure out a way to fix this, so it isn't an issue for future workloads.

**Comment by newling** [comment] 2016-12-22 07:26
Thanks for looking into this. As far as I can tell `m` and `k` are not always the same for the `TN` cases, for example there is `std::make_tuple(5124, 9124, 1760, true, false)` in gemm_bench.cu

**Comment by sharannarang** [comment] 2016-12-22 21:51
Yeah, there are a few cases where this is an issue. I'll need some time to think about how this impacts the benchmark and confirm that we're measuring what was intended. Will get back about this soon. Thanks for bringing this up!

**Comment by maxcuda** [comment] 2017-02-08 17:36
All the TN cases in which m is different from k are computing a different configuration from the one reported in the Excel file and the one computed by the CPU path.
The lines with the X are reporting the GEMM configurations computed, the ones without are reporting the GEMM configurations requested.
Basically for these TN cases,  the reported GPU performances in the Excel spreadsheets are wrong.

~/DeepBench/code/nvidia$ bin/gemm_bench
                         Times
----------------------------------------------------------------------------------------
    m       n      k      a_t     b_t      time (usec)
   5124   9124   1760      1      0
X  1760   9124   5124      1      0        17667
     35   8457   1760      1      0
X  1760   8457     35      1      0         1171
   5124   9124   2048      1      0
X  2048   9124   5124      1      0        21354
     35   8457   2048      1      0
X  2048   8457     35      1      0         1332
   5124   9124   2560      1      0
X  2560   9124   5124      1      0        26059
     35   8457   2560      1      0
X  2560   8457     35      1      0         1667
   5124   9124   4096      1      0
X  4096   9124   5124      1      0        45349
     35   8457   4096      1      0
X  4096   8457     35      1      0         2649
   7680     16   2560      1      0
X  2560     16   7680      1      0          418
   7680     32   2560      1      0
X  2560     32   7680      1      0          946
   7680     64   2560      1      0
X  2560     64   7680      1      0          600
   7680    128   2560      1      0
X  2560    128   7680      1      0          909
   3072     16   1024      1      0
X  1024     16   3072      1      0           93
   3072     32   1024      1      0
X  1024     32   3072      1      0          377
   3072     64   1024      1      0
X  1024     64   3072      1      0          141
   3072    128   1024      1      0
X  1024    128   3072      1      0          162

**Comment by sharannarang** [comment] 2017-02-09 00:08
Thanks @newling & @maxcuda for pointing out this problem. I've created a PR to address this issue.

**Comment by sharannarang** [comment] 2017-02-13 17:16
I'm closing this issue since I've merged the PR to fix the problem. Thanks for looking into this problem!

**Closed by sharannarang** 2017-02-13 17:16 UTC
